### ISSUE TITLE
Keys aren't properly recognized in other keyboards

### ISSUE THREAD

**Issue by nkovacic99** [emberian/evdev#140]
I am using Dvorak keyboard and xremap only acknowledges what keys are pressed based on the US QWERTY keyboard.

For example, if I want to have combo C-s t to launch Firefox, I have to configure it as:

```yaml
keymap:
  - name: general keybindings
    remap:
      leftctrl-semicolon:
        remap:
          k:
            launch: ["firefox"]
```
